[package]
name = "openseries-lib"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "openseries"

[dependencies]
bitflags.workspace = true
sha2.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
hidapi = { version = "2.6.6", default-features = false, features = ["linux-static-hidraw"] }

[target.'cfg(target_os = "windows")'.dependencies]
hidapi = { version = "2.6.6", default-features = false, features = ["windows-native"] }

[target.'cfg(target_os = "macos")'.dependencies]
hidapi = { version = "2.6.6", default-features = false, features = ["macos-shared-device"] }
